runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: src/index.html
  upload: src/index.html
  secure: always
  redirect_http_response_code: 301

- url: /(.*)
  static_files: src/\1
  upload: src/(.*)
  secure: always
  redirect_http_response_code: 301

